# BDM550 - Final Project

- Name: Ran Arino
- Student ID: 153073200
- Email: rarino@myseneca.ca
- Course: Predictive Analytics
- Course ID: BDM550NAA.05359.2237
- Professor: Dr. Elnaz Delpisheh

In [1]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt

import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import string

from sklearn.decomposition import LatentDirichletAllocation
from sklearn.feature_extraction.text import CountVectorizer


### Data Preprocessing

- Run the Code A if you did not clean the texts
- If you have already created "clean_df.csv"

In [2]:
"""
# load the dataset
a1 = pd.read_csv('articles1.csv')
a2 = pd.read_csv('articles2.csv')
a3 = pd.read_csv('articles3.csv')

# Define function to load and clean text data
#  this is similar function to the one that I used in Workshop05
def clean_texts(raw_texts):
    # define result
    result = []

    # set of stopwords
    stop_words = set(stopwords.words('english'))
    # set porter stemmers
    porter = nltk.PorterStemmer()

    # traversing all sentences
    for sent in raw_texts:
        # tokenize
        tokens = word_tokenize(sent)
        # defined cleaned sentence
        clean_sent = ''
        # cleaning each sentence
        for w in tokens:
            # if 'w' is one of punctuations, skip to the next word
            if w in string.punctuation:
                continue
            # if 'w' is one of stop words, skip to the next word
            if w.lower() in stop_words:
                continue
            # add stemmed word to clean_sent
            clean_sent += porter.stem(w.lower()) + ' '

        # add clean_sent to result (make sure that the last item is always blank)
        result += [clean_sent[:-1]]

    return result

# cleaning the text & put everything into one variable
texts = []

# traversing all files
for df in [a1, a2, a3]:
    texts += clean_texts(df['content'])
    
# store the cleaned data as new df
titles = list(a1['title']) + list(a2['title']) + list(a3['title'])
dates = list(a1['date']) + list(a2['date']) + list(a3['date'])

df_clean = pd.DataFrame({'title': titles, 'date': dates, 'content': texts})
df_clean = clean_df.dropna(subset=['content'])
df_clean.head()

# download the clean_df
#clean_df.to_csv('df_clean.csv', index=False)
"""

"\n# load the dataset\na1 = pd.read_csv('articles1.csv')\na2 = pd.read_csv('articles2.csv')\na3 = pd.read_csv('articles3.csv')\n\n# Define function to load and clean text data\n#  this is similar function to the one that I used in Workshop05\ndef clean_texts(raw_texts):\n    # define result\n    result = []\n\n    # set of stopwords\n    stop_words = set(stopwords.words('english'))\n    # set porter stemmers\n    porter = nltk.PorterStemmer()\n\n    # traversing all sentences\n    for sent in raw_texts:\n        # tokenize\n        tokens = word_tokenize(sent)\n        # defined cleaned sentence\n        clean_sent = ''\n        # cleaning each sentence\n        for w in tokens:\n            # if 'w' is one of punctuations, skip to the next word\n            if w in string.punctuation:\n                continue\n            # if 'w' is one of stop words, skip to the next word\n            if w.lower() in stop_words:\n                continue\n            # add stemmed word to clean_sen

In [3]:
df = pd.read_csv('df_clean.csv')
df.head()

title        date  \
0  House Republicans Fret About Winning Their Hea...  2016-12-31   
1  Rift Between Officers and Residents as Killing...  2017-06-19   
2  Tyrus Wong, ‘Bambi’ Artist Thwarted by Racial ...  2017-01-06   
3  Among Deaths in 2016, a Heavy Toll in Pop Musi...  2017-04-10   
4  Kim Jong-un Says North Korea Is Preparing to T...  2017-01-02   

                                             content  
0  washington — congression republican new fear c...  
1  bullet shell get count blood dri votiv candl b...  
2  walt disney ’ “ bambi ” open 1942 critic prais...  
3  death may great equal ’ necessarili evenhand f...  
4  seoul south korea — north korea ’ leader kim s...

In [8]:
# vectorizing the texts
vect = CountVectorizer()
vect_texts = vect.fit_transform(df['content'])

print(vect_texts.shape)
print(vect_texts[:5].toarray())

(142535, 260539)
[[0 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [9]:
# train the model (20 topics)
lda = LatentDirichletAllocation(n_components=20)
results = lda.fit_transform(vect_texts)

# get topic-word distribution
topic_word_dist = lda.components_
# get document-word distribution
doc_word_dist = lda.transform(vect_texts)